name: satnerf
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - scikit-image
  - numpy
  - matplotlib
  - imageio
  - configargparse
  - tqdm
  - pyvista
  - rasterio
  - gdal
  - pandas
  - scipy
